// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7KAvtqerh58BTHMplvd_fSVN_Uc_m_EA',
    appId: '1:488344172437:web:6971b45207b8d3db20e89c',
    messagingSenderId: '488344172437',
    projectId: 'viajeseguro-b204d',
    authDomain: 'viajeseguro-b204d.firebaseapp.com',
    storageBucket: 'viajeseguro-b204d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFydQGLYFGbmcHbRsTSWFKIDNLoiTnRjo',
    appId: '1:488344172437:android:04debce8ea6becdc20e89c',
    messagingSenderId: '488344172437',
    projectId: 'viajeseguro-b204d',
    storageBucket: 'viajeseguro-b204d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_IuFFStodGjyTxKoKZOYNozy73KS8JQ',
    appId: '1:488344172437:ios:5c5176cacb09d00020e89c',
    messagingSenderId: '488344172437',
    projectId: 'viajeseguro-b204d',
    storageBucket: 'viajeseguro-b204d.firebasestorage.app',
    iosClientId: '488344172437-uq5lj2p10ete1q3tagdia98quvauq32b.apps.googleusercontent.com',
    iosBundleId: 'com.example.vApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_IuFFStodGjyTxKoKZOYNozy73KS8JQ',
    appId: '1:488344172437:ios:5c5176cacb09d00020e89c',
    messagingSenderId: '488344172437',
    projectId: 'viajeseguro-b204d',
    storageBucket: 'viajeseguro-b204d.firebasestorage.app',
    iosClientId: '488344172437-uq5lj2p10ete1q3tagdia98quvauq32b.apps.googleusercontent.com',
    iosBundleId: 'com.example.vApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7KAvtqerh58BTHMplvd_fSVN_Uc_m_EA',
    appId: '1:488344172437:web:5dffca0d581aa3e520e89c',
    messagingSenderId: '488344172437',
    projectId: 'viajeseguro-b204d',
    authDomain: 'viajeseguro-b204d.firebaseapp.com',
    storageBucket: 'viajeseguro-b204d.firebasestorage.app',
  );
}
